# Generated by Django 4.0.3 on 2022-03-31 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='MosqueUniversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
                ('contacts', models.CharField(max_length=24, verbose_name='Контакты')),
                ('images', models.ImageField(upload_to='files/images/', verbose_name='Фотографии')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('name', models.CharField(max_length=500, verbose_name='Имя университета')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.category')),
            ],
            options={
                'verbose_name': 'Исламский университет',
                'verbose_name_plural': 'Исламские университеты',
            },
        ),
        migrations.CreateModel(
            name='MosqueRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
                ('contacts', models.CharField(max_length=24, verbose_name='Контакты')),
                ('images', models.ImageField(upload_to='files/images/', verbose_name='Фотографии')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('name', models.CharField(max_length=500, verbose_name='Имя молельной комнаты')),
                ('gender', models.IntegerField(choices=[(0, 'Мужской'), (1, 'Женский')], verbose_name='Пол')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.category')),
            ],
            options={
                'verbose_name': 'Моельная комната',
                'verbose_name_plural': 'Молельные комнаты',
            },
        ),
        migrations.CreateModel(
            name='MosqueLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
                ('contacts', models.CharField(max_length=24, verbose_name='Контакты')),
                ('images', models.ImageField(upload_to='files/images/', verbose_name='Фотографии')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('name', models.CharField(max_length=500, verbose_name='Имя библиотеки')),
                ('work_time', models.TimeField(verbose_name='Время работы')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.category')),
            ],
            options={
                'verbose_name': 'Исламская библиотека',
                'verbose_name_plural': 'Исламские библиотеки',
            },
        ),
        migrations.CreateModel(
            name='MosqueCollege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
                ('contacts', models.CharField(max_length=24, verbose_name='Контакты')),
                ('images', models.ImageField(upload_to='files/images/', verbose_name='Фотографии')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('name', models.CharField(max_length=500, verbose_name='Имя колледжа')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.category')),
            ],
            options={
                'verbose_name': 'Исламский колледж',
                'verbose_name_plural': 'Исламские колледжи',
            },
        ),
        migrations.CreateModel(
            name='Mosque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
                ('contacts', models.CharField(max_length=24, verbose_name='Контакты')),
                ('images', models.ImageField(upload_to='files/images/', verbose_name='Фотографии')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('name', models.CharField(max_length=500, verbose_name='Имя мечети')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.category')),
            ],
            options={
                'verbose_name': 'Мечеть',
                'verbose_name_plural': 'Мечети',
            },
        ),
        migrations.CreateModel(
            name='Madrasah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
                ('contacts', models.CharField(max_length=24, verbose_name='Контакты')),
                ('images', models.ImageField(upload_to='files/images/', verbose_name='Фотографии')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('name', models.CharField(max_length=500, null=True, verbose_name='Имя медресе')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.category')),
            ],
            options={
                'verbose_name': 'Медресе',
                'verbose_name_plural': 'Медресе',
            },
        ),
    ]
