# Generated by Django 4.0.3 on 2022-04-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_alter_madrasah_images_alter_madrasah_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='madrasah',
            name='images',
            field=models.URLField(verbose_name='Фотографии'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='images',
            field=models.URLField(verbose_name='Фотографии'),
        ),
        migrations.AlterField(
            model_name='mosquecollege',
            name='images',
            field=models.URLField(verbose_name='Фотографии'),
        ),
        migrations.AlterField(
            model_name='mosquelibrary',
            name='images',
            field=models.URLField(verbose_name='Фотографии'),
        ),
        migrations.AlterField(
            model_name='mosqueroom',
            name='images',
            field=models.URLField(verbose_name='Фотографии'),
        ),
        migrations.AlterField(
            model_name='mosqueuniversity',
            name='images',
            field=models.URLField(verbose_name='Фотографии'),
        ),
    ]
