# Generated by Django 4.0.3 on 2022-03-30 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='FastFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название фаст-фуд')),
                ('workTime', models.CharField(max_length=200, verbose_name='Режим работы от/до')),
                ('site', models.URLField(max_length=100, verbose_name='Сайт')),
                ('certificate', models.BooleanField(default=True, verbose_name='Сертификат халал присутствует')),
                ('mosqueRoom', models.BooleanField(default=True, verbose_name='Намазкана есть/нет')),
                ('contacts', models.CharField(max_length=16, verbose_name='Контакты')),
                ('address', models.CharField(max_length=500, verbose_name='Адресс')),
                ('images', models.ImageField(upload_to=None, verbose_name='Фотографии')),
                ('longitude', models.DecimalField(decimal_places=100, max_digits=1000, verbose_name='Долгота')),
                ('latitude', models.DecimalField(decimal_places=100, max_digits=1000, verbose_name='Широта')),
            ],
            options={
                'verbose_name': 'Фаст Фуд',
                'verbose_name_plural': 'Фаст Фуды',
            },
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название магазина/нипермаркета')),
                ('site', models.CharField(max_length=100, verbose_name='Сайт магазина/гипермаркета')),
                ('alcohol', models.BooleanField(default=False, verbose_name='Спритное продается да/нет')),
                ('productsCertificate', models.BooleanField(default=True, verbose_name='Продукты халалные  есть/нет')),
                ('workTime', models.CharField(max_length=200, verbose_name='Режим работы от/до')),
                ('certificate', models.BooleanField(default=True, verbose_name='Сертификат халал присутствует')),
                ('mosqueRoom', models.BooleanField(default=True, verbose_name='Намазкана есть/нет')),
                ('contacts', models.CharField(max_length=16, verbose_name='Контакты')),
                ('address', models.CharField(max_length=500, verbose_name='Адресс')),
                ('images', models.ImageField(upload_to=None, verbose_name='Фотографии')),
                ('longitude', models.DecimalField(decimal_places=100, max_digits=1000, verbose_name='Долгота')),
                ('latitude', models.DecimalField(decimal_places=100, max_digits=1000, verbose_name='Широта')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название ресторана')),
                ('bigHall', models.IntegerField(default=80, verbose_name='Банкетный зал на сколько человек?')),
                ('certificate', models.BooleanField(default=True, verbose_name='Сертификат халал присутствует')),
                ('mosqueRoom', models.BooleanField(default=True, verbose_name='Намазкана есть/нет')),
                ('contacts', models.CharField(max_length=16, verbose_name='Контакты')),
                ('address', models.CharField(max_length=500, verbose_name='Адресс')),
                ('images', models.ImageField(upload_to=None, verbose_name='Фотографии')),
                ('longitude', models.DecimalField(decimal_places=100, max_digits=1000, verbose_name='Долгота')),
                ('latitude', models.DecimalField(decimal_places=100, max_digits=1000, verbose_name='Широта')),
            ],
            options={
                'verbose_name': 'Ресторан',
                'verbose_name_plural': 'Рестораны',
            },
        ),
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название кафе')),
                ('certificate', models.BooleanField(default=True, verbose_name='Сертификат халал присутствует')),
                ('mosqueRoom', models.BooleanField(default=True, verbose_name='Намазкана есть/нет')),
                ('contacts', models.CharField(max_length=16, verbose_name='Контакты')),
                ('address', models.CharField(max_length=500, verbose_name='Адресс')),
                ('images', models.ImageField(upload_to=None, verbose_name='Фотографии')),
                ('longitude', models.DecimalField(decimal_places=100, max_digits=1000, verbose_name='Долгота')),
                ('latitude', models.DecimalField(decimal_places=100, max_digits=1000, verbose_name='Широта')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafes.category', verbose_name='какая категория')),
            ],
            options={
                'verbose_name': 'Кафе',
                'verbose_name_plural': 'Кафе',
            },
        ),
    ]
