# Generated by Django 4.0.3 on 2022-04-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название кафе')),
                ('certificate', models.BooleanField(default=True, verbose_name='Сертификат халал присутствует')),
                ('mosqueroom', models.BooleanField(default=True, verbose_name='Намазкана есть/нет')),
                ('contacts', models.CharField(max_length=16, verbose_name='Контакты')),
                ('address', models.CharField(max_length=500, verbose_name='Адресс')),
                ('images', models.ImageField(upload_to='', verbose_name='Фотографии')),
                ('latitude', models.FloatField(blank=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, verbose_name='Долгота')),
                ('is_published', models.BooleanField(default=False, verbose_name='активировать')),
            ],
            options={
                'verbose_name': 'Кафе',
                'verbose_name_plural': 'Кафе',
            },
        ),
        migrations.CreateModel(
            name='FastFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название фаст-фуд')),
                ('worktime', models.CharField(max_length=200, verbose_name='Режим работы от/до')),
                ('site', models.URLField(blank=True, max_length=100, verbose_name='Сайт')),
                ('certificate', models.BooleanField(default=True, verbose_name='Сертификат халал присутствует')),
                ('mosqueroom', models.BooleanField(default=True, verbose_name='Намазкана есть/нет')),
                ('contacts', models.CharField(max_length=16, verbose_name='Контакты')),
                ('address', models.CharField(max_length=500, verbose_name='Адресс')),
                ('images', models.ImageField(upload_to=None, verbose_name='Фотографии')),
                ('latitude', models.FloatField(blank=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, verbose_name='Долгота')),
                ('is_published', models.BooleanField(default=False, verbose_name='активировать')),
            ],
            options={
                'verbose_name': 'Фаст Фуд',
                'verbose_name_plural': 'Фаст Фуды',
            },
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название магазина/нипермаркета')),
                ('site', models.CharField(blank=True, max_length=100, verbose_name='Сайт магазина/гипермаркета')),
                ('alcohol', models.BooleanField(default=False, verbose_name='Спритное продается да/нет')),
                ('productsCertificate', models.BooleanField(default=True, verbose_name='Продукты халалные  есть/нет')),
                ('worktime', models.CharField(max_length=200, verbose_name='Режим работы от/до')),
                ('certificate', models.BooleanField(default=True, verbose_name='Сертификат халал присутствует')),
                ('mosqueroom', models.BooleanField(default=True, verbose_name='Намазкана есть/нет')),
                ('contacts', models.CharField(max_length=16, verbose_name='Контакты')),
                ('address', models.CharField(max_length=500, verbose_name='Адресс')),
                ('images', models.ImageField(upload_to=None, verbose_name='Фотографии')),
                ('latitude', models.FloatField(blank=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, verbose_name='Долгота')),
                ('is_published', models.BooleanField(default=False, verbose_name='активировать')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название ресторана')),
                ('bighall', models.IntegerField(default=80, verbose_name='Банкетный зал на сколько человек?')),
                ('certificate', models.BooleanField(default=True, verbose_name='Сертификат халал присутствует')),
                ('mosqueroom', models.BooleanField(default=True, verbose_name='Намазкана есть/нет')),
                ('contacts', models.CharField(max_length=16, verbose_name='Контакты')),
                ('address', models.CharField(max_length=500, verbose_name='Адресс')),
                ('images', models.ImageField(upload_to=None, verbose_name='Фотографии')),
                ('latitude', models.FloatField(blank=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, verbose_name='Долгота')),
                ('is_published', models.BooleanField(default=False, verbose_name='активировать')),
            ],
            options={
                'verbose_name': 'Ресторан',
                'verbose_name_plural': 'Рестораны',
            },
        ),
    ]
