# Generated by Django 4.0.3 on 2022-03-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='FastFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.BooleanField(default=True, verbose_name='Сертификат халал присутствует')),
                ('mosqueRoom', models.BooleanField(default=True, verbose_name='Намазкана есть/нет')),
                ('contacts', models.CharField(max_length=16, verbose_name='Контакты')),
                ('address', models.CharField(max_length=500, verbose_name='Адресс')),
                ('images', models.ImageField(upload_to='', verbose_name='Фотографии')),
                ('name', models.CharField(max_length=300, verbose_name='Название фаст-фуд')),
                ('workTime', models.CharField(max_length=200, verbose_name='Режим работы от/до')),
                ('site', models.CharField(max_length=100, verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Фаст Фуд',
                'verbose_name_plural': 'Фаст Фуды',
            },
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.BooleanField(default=True, verbose_name='Сертификат халал присутствует')),
                ('mosqueRoom', models.BooleanField(default=True, verbose_name='Намазкана есть/нет')),
                ('contacts', models.CharField(max_length=16, verbose_name='Контакты')),
                ('address', models.CharField(max_length=500, verbose_name='Адресс')),
                ('images', models.ImageField(upload_to='', verbose_name='Фотографии')),
                ('name', models.CharField(max_length=300, verbose_name='Название магазина/нипермаркета')),
                ('site', models.CharField(max_length=100, verbose_name='Сайт магазина/гипермаркета')),
                ('alcohol', models.BooleanField(default=False, verbose_name='Спритное продается да/нет')),
                ('productsCertificate', models.BooleanField(default=True, verbose_name='Продукты халалные  есть/нет')),
                ('workTime', models.CharField(max_length=200, verbose_name='Режим работы от/до')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.CreateModel(
            name='MosqueCafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.BooleanField(default=True, verbose_name='Сертификат халал присутствует')),
                ('mosqueRoom', models.BooleanField(default=True, verbose_name='Намазкана есть/нет')),
                ('contacts', models.CharField(max_length=16, verbose_name='Контакты')),
                ('address', models.CharField(max_length=500, verbose_name='Адресс')),
                ('images', models.ImageField(upload_to='', verbose_name='Фотографии')),
                ('name', models.CharField(max_length=300, verbose_name='Название кафе')),
            ],
            options={
                'verbose_name': 'Кафе',
                'verbose_name_plural': 'Кафе',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.BooleanField(default=True, verbose_name='Сертификат халал присутствует')),
                ('mosqueRoom', models.BooleanField(default=True, verbose_name='Намазкана есть/нет')),
                ('contacts', models.CharField(max_length=16, verbose_name='Контакты')),
                ('address', models.CharField(max_length=500, verbose_name='Адресс')),
                ('images', models.ImageField(upload_to='', verbose_name='Фотографии')),
                ('name', models.CharField(max_length=300, verbose_name='Название ресторана')),
                ('bigHall', models.IntegerField(default=0, verbose_name='Банкетный зал на сколько человек?')),
                ('latitude', models.FloatField(verbose_name='Широта')),
            ],
            options={
                'verbose_name': 'Ресторан',
                'verbose_name_plural': 'Рестораны',
            },
        ),
    ]
