# Generated by Django 4.0.3 on 2022-03-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
