# Generated by Django 4.0.3 on 2022-03-31 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafe',
            old_name='mosqueRoom',
            new_name='mosqueroom',
        ),
        migrations.RenameField(
            model_name='fastfood',
            old_name='mosqueRoom',
            new_name='mosqueroom',
        ),
        migrations.RenameField(
            model_name='fastfood',
            old_name='workTime',
            new_name='worktime',
        ),
        migrations.RenameField(
            model_name='magazine',
            old_name='mosqueRoom',
            new_name='mosqueroom',
        ),
        migrations.RenameField(
            model_name='magazine',
            old_name='workTime',
            new_name='worktime',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='bigHall',
            new_name='bighall',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='mosqueRoom',
            new_name='mosqueroom',
        ),
    ]
