# Generated by Django 4.0.3 on 2022-04-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='images',
            field=models.ImageField(upload_to=None, verbose_name='Фотографии'),
        ),
    ]
