# Generated by Django 4.0.3 on 2022-03-30 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastfood',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cafes.category', verbose_name='какая категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='magazine',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cafes.category', verbose_name='какая категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cafes.category', verbose_name='какая категория'),
            preserve_default=False,
        ),
    ]
