# Generated by Django 4.0.3 on 2022-03-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0002_fastfood_latitude_fastfood_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosquecafe',
            name='latitude',
            field=models.FloatField(default=1, verbose_name='Широта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mosquecafe',
            name='longitude',
            field=models.FloatField(default=1, verbose_name='Долгота'),
            preserve_default=False,
        ),
    ]
