# Generated by Django 4.0.3 on 2022-04-02 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0002_cafe_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastfood',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='magazine',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
