# Generated by Django 4.0.3 on 2022-04-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0003_alter_cafe_latitude_alter_cafe_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='images',
            field=models.ImageField(upload_to='media', verbose_name='Фотографии'),
        ),
        migrations.AlterField(
            model_name='fastfood',
            name='images',
            field=models.ImageField(upload_to='media', verbose_name='Фотографии'),
        ),
        migrations.AlterField(
            model_name='fastfood',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='fastfood',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='images',
            field=models.ImageField(upload_to='media', verbose_name='Фотографии'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='images',
            field=models.ImageField(upload_to='media', verbose_name='Фотографии'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
    ]
