# Generated by Django 4.0.3 on 2022-04-02 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0003_fastfood_is_published_magazine_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='активном состоянии'),
        ),
    ]
