# Generated by Django 4.0.3 on 2022-03-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0004_alter_fastfood_latitude_alter_fastfood_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fastfood',
            name='site',
            field=models.URLField(max_length=100, verbose_name='Сайт'),
        ),
    ]
