# Generated by Django 4.0.3 on 2022-04-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0004_alter_cafe_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='category',
        ),
        migrations.RemoveField(
            model_name='fastfood',
            name='category',
        ),
        migrations.RemoveField(
            model_name='magazine',
            name='category',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='category',
        ),
        migrations.AlterField(
            model_name='cafe',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='активировать'),
        ),
        migrations.AlterField(
            model_name='fastfood',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='активировать'),
        ),
        migrations.AlterField(
            model_name='fastfood',
            name='site',
            field=models.URLField(blank=True, max_length=100, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='активировать'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='site',
            field=models.CharField(blank=True, max_length=100, verbose_name='Сайт магазина/гипермаркета'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='активировать'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
