# Generated by Django 4.0.3 on 2022-04-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0004_alter_cafe_images_alter_fastfood_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Состаяние публикации'),
        ),
        migrations.AlterField(
            model_name='fastfood',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Состаяние публикации'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Состаяние публикации'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Состаяние публикации'),
        ),
    ]
