# Generated by Django 4.0.3 on 2022-03-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0005_alter_fastfood_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fastfood',
            name='images',
        ),
        migrations.RemoveField(
            model_name='magazine',
            name='images',
        ),
        migrations.RemoveField(
            model_name='mosquecafe',
            name='images',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='images',
        ),
        migrations.AddField(
            model_name='fastfood',
            name='field_name',
            field=models.ImageField(default=1, upload_to=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='magazine',
            name='field_name',
            field=models.ImageField(default=1, upload_to=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mosquecafe',
            name='field_name',
            field=models.ImageField(default=1, upload_to=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='field_name',
            field=models.ImageField(default=1, upload_to=None),
            preserve_default=False,
        ),
    ]
