# Generated by Django 4.0.3 on 2022-04-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0005_alter_cafe_is_published_alter_fastfood_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='images',
            field=models.URLField(verbose_name='Фотографии'),
        ),
        migrations.AlterField(
            model_name='fastfood',
            name='images',
            field=models.URLField(verbose_name='Фотографии'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='images',
            field=models.URLField(verbose_name='Фотографии'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='images',
            field=models.URLField(verbose_name='Фотографии'),
        ),
    ]
