# Generated by Django 4.0.3 on 2022-04-09 05:21

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('company', models.CharField(max_length=500, verbose_name='Компания')),
                ('requirements', models.TextField(max_length=1000, verbose_name='Требования')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Зарплата')),
                ('adress', models.CharField(max_length=250, verbose_name='Адрес')),
                ('time_work', models.CharField(max_length=200, verbose_name='рабочее время')),
                ('number', models.CharField(max_length=100, verbose_name='Номер телефона')),
                ('education', models.TextField(verbose_name='образование')),
                ('duties', models.TextField(verbose_name='Обязанности')),
                ('conditions', models.TextField(max_length=1000, verbose_name='Условия работы')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('fio', models.CharField(max_length=200, verbose_name='ФИО')),
                ('dateofbirth', models.DateField(verbose_name='Дата рождения')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('workexperience', models.CharField(max_length=255, verbose_name='Стаж работы')),
                ('levelstudies', models.CharField(max_length=100, verbose_name='Уровень образования')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.vacancy', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'данные пользователя',
                'verbose_name_plural': 'данные пользователей',
            },
        ),
    ]
