# Generated by Django 4.0.3 on 2022-03-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('company', models.CharField(max_length=500, verbose_name='Компания')),
                ('requirements', models.TextField(max_length=1000, verbose_name='Требования')),
                ('salary', models.IntegerField(default=0, verbose_name='Зарплата')),
                ('duties', models.TextField(verbose_name='Обязанности')),
                ('conditions', models.TextField(max_length=1000, verbose_name='Условия для религиозных')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
