# Generated by Django 4.0.3 on 2022-03-29 07:40

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('fio', models.CharField(max_length=200, verbose_name='ФИО')),
                ('dateofbirth', models.DateField(verbose_name='Дата рождения')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('workexperience', models.CharField(max_length=255, verbose_name='Стаж работы')),
                ('levelstudies', models.CharField(max_length=100, verbose_name='Уровень образования')),
            ],
            options={
                'verbose_name': 'данные пользователя',
                'verbose_name_plural': 'данные пользователей',
            },
        ),
    ]
