# Generated by Django 4.0.3 on 2022-03-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='adress',
            field=models.CharField(default=1, max_length=250, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='education',
            field=models.TextField(default=1, verbose_name='образование'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='number',
            field=models.CharField(default=1, max_length=100, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='time_work',
            field=models.CharField(default=1, max_length=200, verbose_name='рабочее время'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='conditions',
            field=models.TextField(max_length=1000, verbose_name='Условия работы'),
        ),
    ]
