# Generated by Django 4.0.3 on 2022-03-29 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='vacancy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vacancies.vacancy'),
            preserve_default=False,
        ),
    ]
