# Generated by Django 4.0.3 on 2022-03-29 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_registration_vacancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='vacancy',
        ),
        migrations.CreateModel(
            name='ChoiceRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.registration')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.vacancy')),
            ],
        ),
    ]
