# Generated by Django 4.0.3 on 2022-03-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_registration_vacancy_delete_choiceregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Зарплата'),
        ),
    ]
